blank_issues_enabled: true
contact_links:
  - name: Need Help?
    url: https://discord.com/invite/KKucsCpZmY
    about: Chat with us in \#nft-storage on IPFS discord.
  - name: Pinning Service Access Request
    url: https://mailxto.com/i0385q
    about: Submit a request to access the NFT.Storage IPFS pinning service in your account!
