# nftstorage.link api wrangler config.
name = "nftstorage-link-api"
main = "./dist/worker.mjs"
compatibility_date = "2022-05-11"

[build]
command = "npm run build"

# PROD!
[env.production]
# name = "nftstorage-link-api-production"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
route = "api.nftstorage.link/*"
kv_namespaces = [
  { binding = "DENYLIST", id = "785cf627e913468ca5319523ae929def" }
]

[env.production.vars]
DATABASE_URL = "https://nft-link-prod.herokuapp.com"
NFT_STORAGE_API = "https://api.nft.storage"
DEBUG = "false"
ENV = "production"
GATEWAY_DOMAIN = "nftstorage.link"

[[env.production.r2_buckets]]
bucket_name = "super-hot"
binding = "SUPERHOT"

[[env.production.bindings]]
name = "GATEWAY"
type = "service"
service = "gateway-nft-storage-production"
environment = "production"

# Staging!
[env.staging]
# name = "nftstorage-link-api-staging"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
route = "api-staging.nftstorage.link/*"
kv_namespaces = [
  { binding = "DENYLIST", id = "f4eb0eca32e14e28b643604a82e00cb3" }
]

[env.staging.vars]
DATABASE_URL = "https://nft-link-staging.herokuapp.com"
NFT_STORAGE_API = "https://api-staging.nft.storage"
DEBUG = "true"
ENV = "staging"
GATEWAY_DOMAIN = "nftstorage.link"

[[env.staging.r2_buckets]]
bucket_name = "super-hot-staging"
binding = "SUPERHOT"

[[env.staging.bindings]]
name = "GATEWAY"
type = "service"
service = "gateway-nft-storage-staging"
environment = "production"

# Test!
[env.test]
workers_dev = true

[env.test.vars]
DEBUG = "true"
ENV = "test"
GATEWAY_DOMAIN = "localhost:9081"

# Dev!
[env.vsantos]
workers_dev = true
account_id = "7ec0b7cf2ec201b2580374e53ba5f37b"

[env.vsantos.vars]
DEBUG = "true"
ENV = "test"
GATEWAY_DOMAIN = "nftstorage.link"