GRANT USAGE ON SCHEMA public TO stats;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO stats;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO stats;

GRANT USAGE ON SCHEMA nftstorage TO stats;
GRANT SELECT ON ALL TABLES IN SCHEMA nftstorage TO stats;
ALTER DEFAULT PRIVILEGES IN SCHEMA nftstorage GRANT SELECT ON TABLES TO stats;
