name: Website
on:
  push:
    branches:
      - main
    paths:
      - 'packages/website/**'
  pull_request:
    paths:
      - 'packages/website/**'

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.x
      - uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
      - run: pnpm install
      - name: Run build
        env:
          # Fake environment vars required for build
          NEXT_PUBLIC_ENV: dev
        run: pnpm build:website
      - name: Run test
        run: pnpm test:website
  test-e2e:
    name: ${{ matrix.os }} (${{ matrix.browser }})
    strategy:
      fail-fast: false
      matrix:
        browser:
          - firefox
          - chromium
        os:
          - ubuntu-18.04
        node-version:
          - 16
        test_results_path:
          # corresponds to playwright invocation/configuration
          - packages/website/test-results
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.x
      - uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}
      - run: pnpm install
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npx playwright install --with-deps ${{ matrix.browser }} chromium
        working-directory: packages/website
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm --filter website run test:e2e -- --project=${{ matrix.browser }}
      - name: Check for website test results
        id: check_website_test_results
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ matrix.test_results_path }}
      - if: steps.check_website_test_results.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.browser }}-${{ matrix.os }}-test-results
          path: ${{ matrix.test_results_path }}
